Repository FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV, pull requests merged in 2023-10, with the labels that each got.

#1 [fix] Github actions add develop branch
  .github/workflows/gradle.yml
  README.md
Labels: bug

#4 responseDTO 와 errorResponseDTO 추가하였습니다.
  src/main/java/com/fastcampus/toyproject/common/dto/ErrorResponseDTO.java
  src/main/java/com/fastcampus/toyproject/common/dto/ResponseDTO.java
  src/main/java/com/fastcampus/toyproject/common/exception/DefaultException.java
  src/main/java/com/fastcampus/toyproject/common/exception/DefaultExceptionHandler.java
  src/main/java/com/fastcampus/toyproject/common/exception/ExceptionCode.java
Labels: feat

#7 여정 관련 클래스들 (요청 DTO, 컨트롤러, 서비스, 레포지토리) 추가 및 여정 순서 검증 메소드 추가하였어요
  src/main/java/com/fastcampus/toyproject/common/config/JPAConfig.java
  src/main/java/com/fastcampus/toyproject/common/exception/ExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryContoller.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryController.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryRequestDTO.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Lodgement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Movement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Stay.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/repository/ItineraryRepository.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/repository/LodgementRepository.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/repository/MovementRepository.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/repository/StayRepository.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryService.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/util/ItineraryValidation.java
  src/test/java/com/fastcampus/toyproject/domain/itinerary/util/ItineraryValidationTest.java
Labels: feat

#9 [refactor] JPAConfig.java 파일 위치 이동
  src/main/java/com/fastcampus/toyproject/config/jpa/JPAConfig.java
Labels: refactor

#10 [refactor] 엔티티들의 컬럼과 관계를 명확히 정의
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Itinerary.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Lodgement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Movement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Stay.java
  src/main/java/com/fastcampus/toyproject/domain/member/entity/Member.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
Labels: refactor

#11 [refactor] 상속관계 엔티티를 superBuilder로 수정
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Itinerary.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Lodgement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Movement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Stay.java
Labels: refactor

#13 [Feature] 여행 정보를 등록, 수정, 삭제한다.
  src/main/java/com/fastcampus/toyproject/common/dto/ErrorResponseDTO.java
  src/main/java/com/fastcampus/toyproject/domain/trip/controller/TripController.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripDTO.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/main/java/com/fastcampus/toyproject/domain/trip/repository/TripRepository.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
Labels: feat, refactor

#16 [Refactor] memberId 추가 및 isDomestic 오류 해결
  src/main/java/com/fastcampus/toyproject/common/BaseTimeEntity.java
  src/main/java/com/fastcampus/toyproject/common/exception/ExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/trip/controller/TripController.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripDTO.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
Labels: fix, feat, refactor

#15 [Feat] 여정들 삽입 부분 1차 완성했습니다. (멤버 로직 추가) (테스트 완)
  src/main/java/com/fastcampus/toyproject/common/exception/ExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryController.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryRequest.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/LodgementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/MovementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/StayResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/repository/ItineraryRepository.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryService.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/util/ItineraryValidation.java
  src/main/java/com/fastcampus/toyproject/domain/member/controller/MemberController.java
  src/main/java/com/fastcampus/toyproject/domain/member/service/MemberService.java
  src/test/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryResponseTest.java
  src/test/java/com/fastcampus/toyproject/domain/itinerary/util/ItineraryValidationTest.java
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary-create.http
  src/test/java/com/fastcampus/toyproject/http_requests/itnerary-create2.http
  src/test/java/com/fastcampus/toyproject/http_requests/member-create-test.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip-create.http
Labels: feat

#19 [Feat] 여정들 삭제 부분 구현했습니다.
  src/main/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryController.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Itinerary.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/repository/ItineraryRepository.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryService.java
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary-delete.http
Labels: feat

#20 [fix] 회의대로 여정 이동 테이블(엔티티) 필드 수정했습니다.
  src/main/java/com/fastcampus/toyproject/common/exception/ExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryRequest.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/LodgementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/MovementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/StayResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Movement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryService.java
Labels: fix, refactor

#25 [test] 기본 테스트용 데이터 SQL 추가
  src/main/resources/import.sql
Labels: test

#24 [fix] 여정 baseEntity 상속 관련 코드 수정
  src/main/java/com/fastcampus/toyproject/common/BaseTimeEntity.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Itinerary.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
Labels: fix

#26 [Refactor] DTO분리, 여행 날짜 타입 수정
  src/main/java/com/fastcampus/toyproject/common/BaseTimeEntity.java
  src/main/java/com/fastcampus/toyproject/domain/trip/controller/TripController.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripDTO.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripDetailDTO.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripRequestDTO.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripResponseDTO.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
Labels: refactor

#27 [Feature] 회원 등록 기능 추가
  src/main/java/com/fastcampus/toyproject/domain/member/controller/MemberController.java
  src/main/java/com/fastcampus/toyproject/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/fastcampus/toyproject/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/fastcampus/toyproject/domain/member/service/MemberService.java
Labels: feat

#28 [feat] 일시 다루는 공통 유틸리티 클래스 추가
  src/main/java/com/fastcampus/toyproject/common/exception/ExceptionCode.java
  src/main/java/com/fastcampus/toyproject/common/util/DateUtil.java
  src/test/java/com/fastcampus/toyproject/common/util/DateUtilTest.java
Labels: question, feat

#29 [feat&refactor] getAllTrips, getTripDetail 정상 작동 확인 완료
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryResponse.java
  src/main/java/com/fastcampus/toyproject/domain/trip/controller/TripController.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripDetailDTO.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripResponseDTO.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
Labels: feat, refactor

#31 [fix] 여행 여정 다대일 관계 수정 및 리팩토링
  src/main/java/com/fastcampus/toyproject/common/exception/DefaultExceptionHandler.java
  src/main/java/com/fastcampus/toyproject/common/exception/ExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryController.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryRequest.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/LodgementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/MovementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/StayResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Itinerary.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Lodgement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Movement.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Stay.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/repository/ItineraryRepository.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryService.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/type/ItineraryType.java
  src/main/java/com/fastcampus/toyproject/domain/trip/controller/TripController.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary-create.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary-delete.http
  src/test/java/com/fastcampus/toyproject/http_requests/itnerary-create2.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip-create.http
Labels: fix, refactor

#37 [feat] TripControllerTest 작성
  build.gradle
  src/test/java/com/fastcampus/toyproject/domain/trip/TripControllerTest.java
Labels: feat, test

#38 [refactor] 여정 삽입 리팩토링 + 팩토리 메소드 패턴 / 여정 순서 검증부분 수정
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/ItineraryResponseFactory.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/LodgementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/MovementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/StayResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/Itinerary.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/ItineraryFactory.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/repository/ItineraryRepository.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/repository/LodgementRepository.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/repository/MovementRepository.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/repository/StayRepository.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryService.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/util/ItineraryOrderUtil.java
  src/test/java/com/fastcampus/toyproject/domain/itinerary/util/ItineraryOrderUtilTest.java
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary-create.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary-update.http
Labels: fix, refactor

#39 [test] 여정 컨트롤러 테스트 코드
  src/test/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryControllerTest.java
Labels: test

#40 [fix] 여정 삭제 부분 수정 + test 파일 생성
  src/main/java/com/fastcampus/toyproject/domain/itinerary/exception/ItineraryExceptionCode.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryService.java
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/create/itinerary-create-fail-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/create/itinerary-create-fail-2.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/create/itinerary-create-fail-3.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/create/itinerary-create-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/create/itinerary-create-success-2.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/create/trip-create-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/create/trip-create-success-2.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/delete/itinerary-delete-fail-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/delete/itinerary-delete-success-1.http
Labels: fix, test

#41 [feature] 코드 통합 & 여행 조회 수정/유틸 에러 처리 수정 완료
  build.gradle
  src/main/java/com/fastcampus/toyproject/ToyprojectApplication.java
  src/main/java/com/fastcampus/toyproject/common/util/LocationUtil.java
  src/main/java/com/fastcampus/toyproject/common/util/api/GoogleApiProperties.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/controller/ItineraryController.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/MovementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
  src/main/resources/application.yml
  src/test/java/com/fastcampus/toyproject/common/util/LocationUtilTest.java
  src/test/java/com/fastcampus/toyproject/domain/trip/controller/TripControllerTest.java
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-fail-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-fail-2.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-fail-3.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/itinerary/insert/itinerary-insert-success-2.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip-delete.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/insert/trip-insert-success-1.http
  src/test/java/com/fastcampus/toyproject/http_requests/trip/insert/trip-insert-success-2.http
Labels: feat

#43 [fix] 최종 테스트 및 오류 수정
  src/main/java/com/fastcampus/toyproject/common/exception/DefaultExceptionHandler.java
  src/main/java/com/fastcampus/toyproject/common/util/DateUtil.java
  src/main/java/com/fastcampus/toyproject/common/util/LocationUtil.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/LodgementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/MovementResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/dto/StayResponse.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/entity/ItineraryFactory.java
  src/main/java/com/fastcampus/toyproject/domain/itinerary/service/ItineraryService.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripDetailResponse.java
  src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripResponse.java
  src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
  src/main/java/com/fastcampus/toyproject/domain/trip/repository/TripRepository.java
  src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
  src/main/resources/application.yml
  src/main/resources/import.sql
  src/main/resources/logback-spring.xml
Labels: fix, refactor
